version: '3'
services:
  express1:
    build: .
    container_name: express1
  
  express2:
    build: .
    container_name: express2


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express1
      - express2
    
    restart: always